app.rb
=> [Routing] Only return 404 if a slim file did not exist

Rakefile, assets/javascripts/search.config.js, assets/stylesheets/search.scss.erb, views/partials/_results.slim
Best to just try this branch. Ping @orta.
=> Adds a sorting selector.

README.md
See https://github.com/CocoaPods/Strata/issues/7#issuecomment-96543526
=> Update README foreman port

app.rb, views/layout.slim
=> Include the name of the pod in the title when under pods/:name

app.rb, lib/pod_quality_estimate.rb
=> [pods/:name/quality] Handle 404

assets/stylesheets/pod.scss.erb
=> Prevent content from(Tables) from spilling out of pod preview 

views/owner.slim
=> Handle 1 Star

app.rb, assets/stylesheets/app.css, assets/stylesheets/pod.scss.erb, assets/stylesheets/quality_indicator.scss.erb, views/owner.slim, views/pod.slim
Fixes #195 
I've just re-discovered the `helper` section of sinatra, that thing is well useful.
* Author Pod are now based on QI
* Author Pods show a description of the pod
* We have an overview of community impact
=> Owners Version 2

assets/stylesheets/about.css.scss.erb
I am not sure if this breaks some other part of the application. The previous commit was from you @orta, I'll add a specific override for about in that case
=> [Code] Fix code formatting breaking lines

assets/javascripts/search.config.js, assets/stylesheets/pod.scss.erb, views/index.slim, views/partials/_search-templates.slim, views/pod.slim
* Updates the copy, mentions the CocoaPods.app
* Adds a close button to search results
* Fixes cropping titles
* Adds status to the footer
=> @me => Homepage Updates

views/index.slim
Updating AFNetworking to 2.6.0. Also adds an example that shows you can point to a patch version in podfile.
=> Update sample podfile to latest version of AFN

views/owner.slim
With no pods
With pods
cc @orta
=> Bring back average quality on owners page

data/contributors.yaml, data/raw_team.yaml, data/team.yaml
=> [Team] Add manuyavuz

views/index.slim
I'm gonna imagine a lot of people will be interested in this.
=> Add a notice on the front page to go to the FAQ for SPM info

app.rb, lib/number_helper.rb
=> Pretty print numbers on pod pages

Gemfile, Gemfile.lock, config.ru, config/rack_attack.rb
Initial implementation. Any feedback is welcome.
CC @orta
=> Implement Rack Attack rate limiting

config/rack_attack.rb, sample.env
Wraps up https://github.com/CocoaPods/cocoapods.org/pull/233
=> Setup rack attack + env vars

views/owner.slim
Moves the logic into a ruby function
=> Fix indentation with owners from PR #236

assets/javascripts/search.config.js
If #220 and #226 come from the search server, I'd rather be extra paranoid against it in the client.
=> [search] Unique the entries in our results

Gemfile, Gemfile.lock, app.rb
Slight bump in page speed by minifying css and js
@orta
=> Minify css and JS in non dev envs

app.rb
It's my understanding that these all use a hash in the file name so caching them for a long time(2 months) should not be problematic.
cc @orta
=> Cache static resources for 2 months

assets/stylesheets/about.css.scss.erb, views/about.slim, views/layout.slim
Fixed some layout bugs, removed twitter follow buttons for now as it's super hard to debug.
=> Update the about page

Rakefile, data/contributors.yaml
=> [Rakefile] Ignore forks when counting commits

Gemfile, Gemfile.lock
to give some time to add support in the Mac app for b6's changes
=> Revert back to beta five

Gemfile, Gemfile.lock
Reverts CocoaPods/cocoapods.org#260 - thanks
=> Revert "Revert back to beta five"

views/app.slim
Source: https://twitter.com/alloy/status/730462765614239746
=> [App] Change MacRuby to RubyCocoa

data/contributors.yaml, data/team.yaml
I wanted to deploy https://github.com/CocoaPods/cocoapods.org/pull/275 so I updated the data in preparation.
=> [Data] Update for a deploy

views/app.slim
- Replaces the *it's* contraction with the *its* possessive
- Fixes a comma splice
=> Fix 2 typos

views/pod.slim
Re: https://github.com/CocoaPods/cocoadocs.org/issues/401#issuecomment-233308026 - I think this is a pretty good idea
=> Renames readme to overview in the tab selector

data/alumni.yaml, data/raw_team.yaml, data/team.yaml
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">🎉 I’m more than excited to announce I’ll be joining the Developer Tools team at  in October! 🎉🛠</p>&mdash; 🍷🐽 (@NeoNacho) <a href="https://twitter.com/NeoNacho/status/758330694057664514">July 27, 2016</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
=> Ya tu sabes

assets/stylesheets/about.css.scss.erb, data/alumni.yaml, data/contributors.yaml, data/raw_alumni.yaml, data/raw_team.yaml, data/team.yaml
it is/was awesome working with you all
@DanToml / @benasher44 - happy to jam with you two on what your tagline is, I generally try to make them alliterate but I'm pretty chill on what this looks like
@benasher44 - would love for you to get yourself a twitter background, if you're not sure of what, I'd love to see a landscape from where you grew up, but you can totally do whatever you want 👍 
fixes #291
=> Migrate a chunk of inactive contributors team to alumni <3 - 

views/index.slim
Given that our activerecord dep is making it hard to use CP < 1.1
=> Use the pre in the example,

assets/javascripts/search.config.js
Meh, reverting another attempt at de-duping on the client side.
"17 results" -> shows 4
=> Undoes #289

spec_extensions.rb
Closes #303.
Manually verified this fixes the issue
=> Use Pod::Source::Metadata to determine podspec path fragment

data/contributors.yaml, data/raw_team.yaml, data/team.yaml
also moves me segiddins and marius down, given that a lot of the decision making is done by @DanToml / @benasher44 / @dnkoutso
=> Adds @dnkoutso to the cocoapods about

views/pod.slim
=> Adds Swift Version metadata if it's available

views/partials/_search-templates.slim, views/pod.slim
=> Remove podspec & nil protections

data/alumni.yaml
=> Updated twitter images

views/app.slim
Updates the links in the app page
=> Update the cocoapods app version

assets/javascripts/application.js, assets/javascripts/search.config.js, assets/stylesheets/search.scss.erb, views/index.slim, views/partials/_results.slim, views/partials/_search-templates.slim
this isn't sped up, it's returning as fast as I can type, dang
Removes picky, drops basically every cool feature we have on top of search and gives a simple list of results. Builds off the work on https://github.com/CocoaPods/indexer.cocoapods.org
=> Adds the simplest implementation of Algolia

app.rb, assets/javascripts/search.config.js
I accidentally shipped some new JS which this breaks on
=> Remove modern js

views/index.slim
See also https://github.com/CocoaPods/cocoapods.org/pull/296.
=> Update “OS X” to “macOS”

app.rb, views/owner.slim, views/pod.slim
Also fixes https://github.com/CocoaPods/cocoapods.org/issues/402 because now all pods are shown - not just ones we have rich metadata for
fixes https://github.com/CocoaPods/cocoapods.org/issues/392
=> Remove the references to the QIs in the authors page

data/alumni.yaml, data/contributors.yaml, data/raw_team.yaml, data/team.yaml
=> Adds amorde to the core team, and the footer

app.rb
Apparently, the way it's been working is that no `Cache-Control` was being set on dynamic content, e.g. pod pages. Turns out this means that CDN was basically just a forward.
This PR adds headers on all requests, 60 seconds CDN-side for dynamic content, reuses the static cache headers for others. 
Let Cloudflare sort them out.
This means that the 403 workaround can possibly be removed but I'd rather see this PR go up first.
=> Add dynamic Content-Cache headers

Gemfile, Gemfile.lock, views/index.slim
Also bump Bundler and other deps necessary to get things working locally
=> Bump Ruby to 2.7.4

spec_extensions.rb
Fixes https://github.com/CocoaPods/cocoapods.org/issues/495
=> Fix error when loading pod homepage due to calling Ruby 2.x API
