views/pod_quality.slim
- Configured rows and cols according to design
- Added 1 `@media` query for the «top score»
This is how it currently looks on an `iPhone 6`:
---
=> Added support for mobile sites (quality view).

views/owner.slim
Owner pages of owners without pods crash. E.g. https://cocoapods.org/owners/2
This provides a fix that lets the page render.
However, it could be argued that an owner without pods should not be rendered, or rendered with completely different information. But I suggest we move onto that after this quick fix.
=> Frh owners page fix

app.rb
Why:
When quality was exactly 100 the previous logic for
calculating the quality indicator group would incorrectly
result in 6 which results in the class `quality_6`.
Closes: #193
=> Fix quality indicator for quality of 100 exactly

views/pod_quality.slim
Think it's pretty annoying to see this in the vast majority of pods, so I'm hiding it for the not applied section.
=> Remove verified QI from the not applied section

app.rb
We were getting a 400 ( probably ) from the QI server while it was being hammered, see #234 - so now we glob a range of 40X replies and give a 404.
=> Handle QIs not giving back a 404

views/index.slim
The current production version of Cocoapods does not work with the current production versions of OS X and Xcode. Documenting that users are expected to install a prelease version will reduce spurious bug reports for issues that have been fixed for months – reference cocoapods/cocoapods#4345 for more information.
=> Update installation instructions on homepage

README.md
Instructions list `clone:cocoapods` but there is no `cocoapods` subtask, it's an argument to Rake. Might have this wrong, please correct otherwise.
=> Fixes README setup instructions

domain.rb, views/index.slim
I also dropped the "about the Swift Package Manager" thing, SwiftPM is no surprise for anyone ATM, and more importantly we're linking to something that says "we'll see" not much to gain from that anymore.
Anyway, it adds some numbers - this is based on my local db, so they're off
It does mean that the front page now triggers 2 db calls, but one is limited to one item, and the other is a count of all rows - which I expect to be fast.
=> Adds some interesting stats to the homepage

Rakefile, assets/javascripts/search.config.js
I think my original implementation a while back was de-duping the `Picky::Allocations` JS object, which is like an array but contains a few useful functions. 
This now de-dupes the content of the picky allocations before sending them into the app's core to start creating the presentation layer.
=> Take another stab at de-duplicating client side

views/index.slim
Now that Cocoapods 1.1.1 is out, there is no need to recommend the release candidate version of cocoapods to support Xcode 7 and 8
=> recommend cocoapods stable version to support Xcode 7 and 8

views/pod.slim
To correlate with CocoaPods/cocoadocs.org#508
* Removes sidebar attributes that we can't reliably show
* The numbers for the pips in the cocoapods will need updating after re-running all QIs in https://github.com/CocoaPods/cocoadocs-api/pull/30
=> Prepare for CocoaDocs' simplification

views/index.slim
Because Xcode 7 is quite old and not many people use it.
=> Update Xcode versions in instructions

assets/javascripts/application.js, assets/javascripts/jquery.cookie.js, assets/javascripts/search.config.js, assets/stylesheets/pod.scss.erb, views/pod.slim, views/pod_page.slim
So I've been chatting with [AppSight](http://appsight.io) for a year or two, and I'd got to a point where it felt like they in a good place and I think AppSight offers something really useful for our pod pages. So I've looked into adding support for AppSight in the sidebar in the least intrusive way possible.
It looks a bit like this:
Which tells you what app it is on hover, and links to their overview page
e.g. https://www.appsight.io/app/bitmoji
the link in the title gives  the appsight page for a lib:  https://www.appsight.io/sdk/bolts
---
This will an opt-in process. By default we check if a cookie has been set, and show a button to enable this. There'll be a way to turn it off too before I make this un-WIP.
=> AppSight integration on a Pod page

views/pod.slim
Re: https://github.com/CocoaPods/trunk.cocoapods.org/pull/238
A row on the CD part of trunk could now be very empty
This handles that. I want to add a bit more metadata but this makes everything work.
=> Adds support for partial cocoadocs data from the cocoapods-metrics-service

.github/ISSUE_TEMPLATE.md, README.md
As CD isn't up anywhere, no need to send people in that direction.
=> Remove the issue template, and the link to cocoadocs

assets/javascripts/search.config.js, views/about.slim, views/layout.slim
We originally added GA when building out CP.org to get a sense of what to focus our attention to when transitioning to the new site, to understand the scope of features used in search and as a potential stat for a Pod for quality metrics - I basically wanted to pass back the numbers to the pod pages about its traffic.
It turned out getting your own data was harder than I expected. So I never succeeded in pulling that off. Shame. 
But all of these cases aren't useful anymore now it's mature, so why are we tracking people on the website? Mainly because we haven't turned it off. Which this now does.
=> Remove Google Analytics, and de-scale the usage of twitter scripts

views/partials/_search.slim
Doing this update now, so it's already deployed before we add the new search
PS. how did we used to get the keywords? I don't seem to see that in any of the json tables
(I guess it would also be nice if I'd have push access to this repo, but not essential since it can be forked)
=> chore: Update capabilities of the search

spec_extensions.rb, views/pod.slim
The cocoadocs has been broken for a while now. This will remove the documentation button when the podspec doesn't specify a documentation url. Fixes issue #380
=> remove documentation button when not specified in podspec

views/pod.slim
It's been a year or so since CocoaDocs was turned off, and so a lot of the quality scores aren't up to date (and also not really used in the new search alogorithm ) 
So, it's better to just not have it anymore.
=> Remove the quality link

views/pod.slim
The ARCore pod page (https://cocoapods.org/pods/ARCore) currently doesn't show the CHANGELOG tab, even though the data is actually there (https://cocoapods.org/pods/ARCore/changelog). The tab switcher should show whenever possible (when there is a CHANGELOG). (Note: the README and CHANGELOG rendering incorrectly in this example are a separate problem fixed here: https://github.com/CocoaPods/cocoapods-metadata-service/pull/20).
=> Show CHANGELOG tab when possible.

assets/javascripts/search.config.js, views/partials/_search-templates.slim, views/partials/_search.slim
When searching for a pod that doesn't have a `/pods/:name` landing page, e.g. `GoogleMobileAdsMediationVerizonMedia`, I get redirected to an external website. 
This prevents me from being able to open the podspec for the pods.
This PR adds an action link to the podspec next to the "Site" link.
=> Add link to podspec in search results

app.rb
Example: https://cocoapods.org/pods/com.aware.ios.sensor.significantmotion (currently triggers a 500 without this fix)
=> Fix exception when attempting to view a Pod for which all versions are unpublished

spec_extensions.rb
See Podspecs link on the website are broken. 
Example: 
https://github.com/CocoaPods/Specs/blob/master/Specs/[%229%22,%20%22c%22,%20%22c%22,%20%22AppLovinSDK%22,%20%3CPod::Version%20version=12.1.0%3E]/AppLovinSDK.podspec.json
Should be
https://github.com/CocoaPods/Specs/blob/master/Specs/9/c/c/AppLovinSDK/12.1.0/AppLovinSDK.podspec.json
https://github.com/CocoaPods/cocoapods.org/assets/3648336/4f8106f7-bcf5-475e-a634-5aeb40e49394
This PR updates the `or_podspec_url` logic to fix this.
=> Fix "See Podspecs" URL on Cocoapods.org website
